const objetosJS = [
    { pregunta: "PLAGA a menos de 3mts", puntos: 5, id: "FS1" },
    { pregunta: "Temperatura de carnes 155F", puntos: 5, id: "FS2" },
    { pregunta: "Temperatura de pollo 165F", puntos: 5, id: "FS3" },
    { pregunta: "Temperatura de pescado N/A", puntos: 5, id: "FS4" },
    { pregunta: "Temperatura de salchicha 165F", puntos: 3, id: "FS5" },
    { pregunta: "Temperatura de huevos 155F y yemas no liquidas", puntos: 5, id: "FS6" },
    { pregunta: "Gtes entrenados en Seguridad de la Comida, integridad, lavado de manos, nuevo sistema digital.", puntos: 5, id: "FS7" },
    { pregunta: "Vida util primaria de todos los productos.", puntos: 5, id: "FS8" },
    { pregunta: "Hay agua corriente y los suministros necesarios en todos los lavamanos", puntos: 5, id: "FS9" },
    { pregunta: "Los Crew se lavan las manos en el momento correcto, procedimiento y registros en tablet y libro.", puntos: 5, id: "FS10" },
    { pregunta: "Baldes con toallas sanitizadas contienen suficientes toallas y solución sanitizante.", puntos: 5, id: "FS11" },
    { pregunta: "Trapos blancos y de parrilla no mas de 1 hora sobre las superficies.", puntos: 5, id: "FS12" },
    { pregunta: "Lavado de utensilios cada 4 horas y tinas del wash con solución sanitizante.", puntos: 3, id: "FS13" },
    { pregunta: "Estado de limpieza del Restaurante, pisos/ paredes/ techo y equipos no tienen polvo/ suciedad/ acumulación", puntos: 3, id: "FS14" },
    { pregunta: "Estado de conservación, el equipo funciona correctamente y en buen estado (no agrietado ni daÃ±ado). Los congeladores no deben tener un exceso de acumulación de hielo.", puntos: 3, id: "FS15" },
    { pregunta: "Los filtros de agua están dentro de la fecha y las maquinas de hielo y pinzas no tienen hongos", puntos: 3, id: "FS16" },
    { pregunta: "Los paquetes abiertos de comida almacenados, (incluyendo seco, refrigeradores y congeladores) están tapados/envueltos, etiquetados, fuera del piso y lejos de las paredes y almacenados siguiendo los procedimientos adecuados.", puntos: 3, id: "FS17" },
    { pregunta: "Uso de guantes azules y espátula amarilla.", puntos: 5, id: "FS18" },
    { pregunta: "Uso de guantes transparentes, mandiles, uñas y uniformes limpios.", puntos: 5, id: "FS19" },
    { pregunta: "Los productos químicos se guardan lejos de la comida y los embalajes ", puntos: 3, id: "FS20" },
    { pregunta: "Programa de Manejo de Plagas, reportes, servicios, permisos, guardapolvos, correcciones de visita hechas.", puntos: 3, id: "FS21" },
    { pregunta: "Hay procedimientos para el derramamiento de productos no alimenticios de riesgo biológico", puntos: 1, id: "FS22" },
    { pregunta: "Temperatura de Congeladores OF-10F o 5", puntos: 5, id: "FS23" },
    { pregunta: "Temperatura de Refrigeradores 34F a 40F", puntos: 5, id: "FS24" },
    { pregunta: "La vida secundaria de todos los productos marcada.", puntos: 3, id: "FS25" },
    { pregunta: "Se descartan los productos del UHC vencidos.", puntos: 3, id: "FS26" },
    { pregunta: "El pirometro y los accesorios (bacterias de repuesto y sonda disponibles)", puntos: 5, id: "FS27" },
    { pregunta: "Alimentos, envases y productos de Proveedores Aprobados", puntos: 5, id: "FS28" },
    { pregunta: "Los Gtes conocen los síntomas de enfermedades de los Crew", puntos: 5, id: "FS29" },
    { pregunta: "Certificados de Seguridad de la Comida de Crew y Gtes.", puntos: 5, id: "FS30" },
    { pregunta: "Listas de Seguridad de la Comida, últimos 60 Dias, sin errores, uso de Tablet.", puntos: 5, id: "FS31" },
    { pregunta: "Informe mÃ¡s reciente del servicio de Inspecciono/Vigilancia Sanitaria", puntos: 5, id: "FS32" }
    
]