export const preguntaAuditoria = [
    { pregunta: "PLAGA a menos de 3mts viva", puntos: "Critico", id: "FS1", RespuestaNegativa: "" },
    { pregunta: "Peligro inminente para la salud (fuego, inundación, riesgo eléctrico, químicos expuestos)", puntos: "Critico", id: "FS2", RespuestaNegativa: "" },
    { pregunta: "Temperatura de almacenamiento (carnes y salchicha para desayuno)", puntos: "Critico", id: "FS3", RespuestaNegativa: "" },
    { pregunta: "Temperatura interna de carnes (10:1, 4:1)", puntos: "Critico", id: "FS4", RespuestaNegativa: "" },
    { pregunta: "Temperatura de salchicha 165°F", puntos: "Critico", id: "FS5", RespuestaNegativa: "" },
    { pregunta: "Temperatura de huevos 155°F y yemas no líquidas", puntos: "Critico", id: "FS6", RespuestaNegativa: "" },
    { pregunta: "Temperatura interna de productos de pollo (165°F mínimo)", puntos: "Critico", id: "FS7", RespuestaNegativa: "" },
    { pregunta: "El entrenamiento de los gerentes se demuestra en base a sus conocimientos para completar la lista", puntos: "Critico", id: "FS8", RespuestaNegativa: "" },
    { pregunta: "El pirometro y las sondas están calibrados y funcionan correctamente", puntos: "Critico", id: "FS9", RespuestaNegativa: "" },
    { pregunta: "Manipulación de producto crudo (Guantes Azules) se usa correctamente", puntos: "Critico", id: "FS10", RespuestaNegativa: "" },
    { pregunta: "Procedimiento correcto de lavado de manos (procedimiento y utensilios)", puntos: 6, id: "FS11", RespuestaNegativa: "" },
    { pregunta: "Baldes con toallas sanitizadas contienen suficientes toallas y solución sanitizante", puntos: 6, id: "FS12", RespuestaNegativa: "" },
    { pregunta: "Limpieza de Área de cocina y cuarto trasero (incluye utensilios)", puntos: 4, id: "FS13", RespuestaNegativa: "" },
    { pregunta: "Limpieza de Área de Servicio", puntos: 4, id: "FS14", RespuestaNegativa: "" },
    { pregunta: "Limpieza de Área de Clientes y Cuarto de empleados", puntos: 4, id: "FS15", RespuestaNegativa: "" },
    { pregunta: "Estado de limpieza del Exterior, pisos/paredes/techo y equipos no tienen polvo/suciedad/acumulación", puntos: 4, id: "FS16", RespuestaNegativa: "" },
    { pregunta: "Estado de conservación de la cocina", puntos: 4, id: "FS17", RespuestaNegativa: "" },
    { pregunta: "Estado de conservación, almacenamiento", puntos: 4, id: "FS18", RespuestaNegativa: "" },
    { pregunta: "Estado de conservación, área de clientes y empleados", puntos: 4, id: "FS19", RespuestaNegativa: "" },
    { pregunta: "Agua y hielo (procedimiento y documentación)", puntos: 6, id: "FS20", RespuestaNegativa: "" },
    { pregunta: "Procedimiento de almacenamiento (producto expuesto y sin contacto con el piso)", puntos: 4, id: "FS21", RespuestaNegativa: "" },
    { pregunta: "Higiene personal (Uniformes, uso de joyería, mandiles)", puntos: 2, id: "FS22", RespuestaNegativa: "" },
    { pregunta: "Peligro biológico no alimenticio (kit de derrames)", puntos: 2, id: "FS23", RespuestaNegativa: "" },
    { pregunta: "Programa de manejo de sustancias químicas (alejados de alimentos y fichas técnicas)", puntos: 4, id: "FS24", RespuestaNegativa: "" },
    { pregunta: "Programa de manejo de plagas (reportes, orden, limpieza y exclusión)", puntos: 4, id: "FS25", RespuestaNegativa: "" },
    { pregunta: "Alimentos, envases y productos de proveedores aprobados", puntos: 4, id: "FS26", RespuestaNegativa: "" },
    { pregunta: "Los gerentes conocen los síntomas de enfermedades para los trabajadores (crew)", puntos: 6, id: "FS27", RespuestaNegativa: "" },
    { pregunta: "Listas de seguridad de la comida (últimos 60 días, 2 verificaciones mensuales)", puntos: 4, id: "FS28", RespuestaNegativa: "" },
    { pregunta: "Certificados de seguridad de la comida Crew y Gtes (entrenamiento)", puntos: 6, id: "FS29", RespuestaNegativa: "" },
    { pregunta: "Gestión de Alérgenos", puntos: 4, id: "FS30", RespuestaNegativa: "" },
    { pregunta: "Grifos sin contacto en el lavado de manos", puntos: 6, id: "FS31", RespuestaNegativa: "" }
];
