export const preguntaAuditoria = [
    { pregunta: "PLAGA a menos de 3mts", puntos: "Critico", id: "FS1", RespuestaNegativa: "" },
    { pregunta: "Temperatura de carnes 155F", puntos: "Critico", id: "FS2", RespuestaNegativa: "" },
    { pregunta: "Temperatura de pollo 165F", puntos: "Critico", id: "FS3", RespuestaNegativa: "" },
    { pregunta: "Temperatura de pescado N/A", puntos: "Critico", id: "FS4", RespuestaNegativa: "" },
    { pregunta: "Temperatura de salchicha 165F", puntos: "Critico", id: "FS5", RespuestaNegativa: "" },
    { pregunta: "Temperatura de huevos 155F y yemas no liquidas", puntos: "Critico", id: "FS6", RespuestaNegativa: "" },
    { pregunta: "Gtes entrenados en Seguridad de la Comida, integridad, lavado de manos, nuevo sistema digital.", puntos: "Critico", id: "FS7", RespuestaNegativa: "" },
    { pregunta: "Vida util primaria de todos los productos.", puntos: "Critico", id: "FS8", RespuestaNegativa: "" },
    { pregunta: "Hay agua corriente y los suministros necesarios en todos los lavamanos", puntos: 5, id: "FS9", RespuestaNegativa: "" },
    { pregunta: "Los Crew se lavan las manos en el momento correcto, procedimiento y registros en tablet y libro.", puntos: 5, id: "FS10", RespuestaNegativa: "" },
    { pregunta: "Baldes con toallas sanitizadas contienen suficientes toallas y solución sanitizante.", puntos: 5, id: "FS11", RespuestaNegativa: "" },
    { pregunta: "Trapos blancos y de parrilla no mas de 1 hora sobre las superficies.", puntos: 5, id: "FS12", RespuestaNegativa: "" },
    { pregunta: "Lavado de utensilios cada 4 horas y tinas del wash con solución sanitizante.", puntos: 3, id: "FS13", RespuestaNegativa: "" },
    { pregunta: "Estado de limpieza del Restaurante, pisos/ paredes/ techo y equipos no tienen polvo/ suciedad/ acumulación", puntos: 3, id: "FS14", RespuestaNegativa: "" },
    { pregunta: "Estado de conservación, el equipo funciona correctamente y en buen estado (no agrietado ni daÃ±ado). Los congeladores no deben tener un exceso de acumulación de hielo.", puntos: 3, id: "FS15", RespuestaNegativa: "" },
    { pregunta: "Los filtros de agua están dentro de la fecha y las maquinas de hielo y pinzas no tienen hongos", puntos: 3, id: "FS16", RespuestaNegativa: "" },
    { pregunta: "Los paquetes abiertos de comida almacenados, (incluyendo seco, refrigeradores y congeladores) están tapados/envueltos, etiquetados, fuera del piso y lejos de las paredes y almacenados siguiendo los procedimientos adecuados.", puntos: 3, id: "FS17", RespuestaNegativa: "" },
    { pregunta: "Uso de guantes azules y espátula amarilla.", puntos: 5, id: "FS18", RespuestaNegativa: "" },
    { pregunta: "Uso de guantes transparentes, mandiles, uñas y uniformes limpios.", puntos: 5, id: "FS19", RespuestaNegativa: "" },
    { pregunta: "Los productos químicos se guardan lejos de la comida y los embalajes ", puntos: 3, id: "FS20", RespuestaNegativa: "" },
    { pregunta: "Programa de Manejo de Plagas, reportes, servicios, permisos, guardapolvos, correcciones de visita hechas.", puntos: 3, id: "FS21", RespuestaNegativa: "" },
    { pregunta: "Hay procedimientos para el derramamiento de productos no alimenticios de riesgo biológico", puntos: 1, id: "FS22", RespuestaNegativa: "" },
    { pregunta: "Temperatura de Congeladores OF-10F o 5", puntos: 5, id: "FS23", RespuestaNegativa: "" },
    { pregunta: "Temperatura de Refrigeradores 34F a 40F", puntos: 5, id: "FS24", RespuestaNegativa: "" },
    { pregunta: "La vida secundaria de todos los productos marcada.", puntos: 3, id: "FS25", RespuestaNegativa: "" },
    { pregunta: "Se descartan los productos del UHC vencidos.", puntos: 3, id: "FS26", RespuestaNegativa: "" },
    { pregunta: "El pirometro y los accesorios (bacterias de repuesto y sonda disponibles)", puntos: 5, id: "FS27", RespuestaNegativa: "" },
    { pregunta: "Alimentos, envases y productos de Proveedores Aprobados", puntos: 5, id: "FS28", RespuestaNegativa: "" },
    { pregunta: "Los Gtes conocen los síntomas de enfermedades de los Crew", puntos: 5, id: "FS29", RespuestaNegativa: "" },
    { pregunta: "Certificados de Seguridad de la Comida de Crew y Gtes.", puntos: 5, id: "FS30", RespuestaNegativa: "" },
    { pregunta: "Listas de Seguridad de la Comida, últimos 60 Dias, sin errores, uso de Tablet.", puntos: 5, id: "FS31", RespuestaNegativa: "" },
    { pregunta: "Informe mas reciente del servicio de Inspecciono/Vigilancia Sanitaria", puntos: 5, id: "FS32", RespuestaNegativa: "" }
];
